version: '3'
services:
  mysqldev:
    image: mysql:5.7
    volumes:
      - ~/mysql/mysql-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: treinamento
      TZ: America/Sao_Paulo
    ports:
      - 13306:3306     
