services:
  keycloak:
    container_name: keycloak-container
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    ports:
      - ${KEYCLOAK_PORT}:8080
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASS}
    volumes:
      - ./src/main/resources/data/keycloak/import/realm-import.json:/opt/keycloak/data/import/realm-import.json
    command:
      - start-dev
      - --import-realm