CREATE TABLE category (
    id VARCHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(500),
    principal varchar(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT 'now()'
);
CREATE TABLE product (
    id VARCHAR(36) PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    price DECIMAL NOT NULL,
    DESCRIPTION VARCHAR(500),
    CATEGORY_ID  VARCHAR(32),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT 'now()',
    FOREIGN KEY (CATEGORY_ID) REFERENCES category(id)
);

INSERT into category values ( '1234','FERRAMENTA','AREA DE FERRAMENTAS','FOOD', now());
INSERT into category values ( '123','ELETROPORT','AREA DE ELETROPORTATEIS','FOOD', now());
INSERT into category values ( '121','CELULAR','AREA DE Celular','FOOD', now());